<?php

/**
 * config.php - dynamic test configuration endpoint (PHP static deployment).
 *
 * Reads the static experiment definition from config_data.php (generated by
 * `lar-export`) and re-applies per-session stimulus sampling
 * (stimuli_per_session / items_per_session) and presentation_order on
 * every request, so each listener gets an independently sampled subset - a
 * static config.json could only ever hand out the same fixed subset to
 * everyone. Mirrors listen_and_rate/routers/api/routes.py's get_test_config().
 *
 * Per-test-type builders are laid out in the project's canonical order:
 * MOS, DMOS, CMOS, AB, ABX, XAB, MUSHRA - shared helpers come first.
 *
 * Like save.php, the functions below are pure (no superglobals/output) so
 * PHPUnit can exercise them directly; only the bottom guard touches output,
 * and only when this file is executed directly.
 */

require_once __DIR__ . '/x_token.php';

// -- Shared helpers ------------------------------------------------------

/** Fisher-Yates shuffle; returns a new array, does not mutate $arr. */
function shuffle_stimuli(array $arr): array
{
    $result = array_values($arr);
    for ($i = count($result) - 1; $i > 0; $i--) {
        $j = random_int(0, $i);
        [$result[$i], $result[$j]] = [$result[$j], $result[$i]];
    }
    return $result;
}

/**
 * Pick one element of $arr at random.
 *
 * Not array_rand(), which draws from PHP's Mersenne Twister: this file draws
 * only through random_int(), because one of its callers picks the stimulus
 * the hidden ABX X duplicates, and x_token.php's HMAC blinding buys nothing
 * if that choice comes from a reconstructible stream. Mirrors
 * listen_and_rate/rng.py.
 */
function pick_one(array $arr)
{
    $values = array_values($arr);
    return $values[random_int(0, count($values) - 1)];
}

/** Randomly choose n distinct elements from arr, preserving their original relative order. */
function sample_keep_order(array $arr, int $n): array
{
    $values = array_values($arr);
    $n = min($n, count($values));
    $indices = range(0, count($values) - 1);
    for ($i = count($indices) - 1; $i > 0; $i--) {
        $j = random_int(0, $i);
        [$indices[$i], $indices[$j]] = [$indices[$j], $indices[$i]];
    }
    $chosen = array_slice($indices, 0, $n);
    sort($chosen);
    return array_map(fn ($i) => $values[$i], $chosen);
}

/**
 * Apply items_per_session-style whole-item sampling: keep every
 * value belonging to $n randomly chosen items, preserving their order.
 * $itemOf extracts a value's item; values with an empty item
 * are dropped. Shared by MOS's stimulus sampling and DMOS's/MUSHRA's trial
 * sampling, mirroring listen_and_rate/routers/api/_shared.py's
 * _sample_trials_by_item().
 */
function sample_by_item(array $values, int $n, callable $itemOf): array
{
    $items = [];
    foreach ($values as $value) {
        $u = $itemOf($value);
        if ($u !== '' && !in_array($u, $items, true)) {
            $items[] = $u;
        }
    }
    $selected = array_flip(sample_keep_order($items, $n));
    return array_values(array_filter(
        $values,
        fn ($value) => isset($selected[$itemOf($value)])
    ));
}

/**
 * Map a stimulus to its public (browser-facing) shape.
 *
 * Only id/label/audio_url are exposed - item and (if ever present)
 * system are withheld to keep listeners blind to the underlying system under
 * test, matching the FastAPI backend's /api/config (audio_url is required
 * here, unlike the FastAPI backend, since the static deployment has no
 * dynamic /audio/{id} fallback route).
 */
function stimulus_to_public(array $s): array
{
    return ['id' => $s['id'], 'label' => $s['label'] ?? null, 'audio_url' => $s['audio_url']];
}

/**
 * Build the practice_* response fields shared by every test type, mirroring
 * listen_and_rate/routers/api/_shared.py's _practice_extras(). Practice pages are
 * drawn from the full $pool (all stimuli/trials) independently of the
 * session sampling, so overlap with the real session is allowed; the
 * shuffle also randomizes their order. Returns [] when no practice stage is
 * configured (practice_count is 0, or absent in pre-practice
 * config_data.php bundles), keeping the response unchanged.
 */
function practice_extras(array $data, array $pool, callable $toResponse, string $key = 'practice_trials'): array
{
    $count = $data['practice_count'] ?? 0;
    if ($count <= 0) {
        return [];
    }
    $sampled = array_slice(shuffle_stimuli($pool), 0, $count);
    return [
        $key => $toResponse($sampled),
        'practice_instructions' => $data['practice_instructions'],
    ];
}

/**
 * Stateless fingerprint of the static config_data.php content, for client-side
 * resume. Hashing the whole bundle (stable per deployment) yields the same
 * value on every request and changes whenever the experiment is re-exported
 * with a different config - so a saved in-progress session can tell whether it
 * still matches. Mirrors listen_and_rate/routers/api/_shared.py's _config_version();
 * the two backends need not agree, since a session only resumes against the
 * same deployment that saved it.
 */
function config_version(array $data): string
{
    return substr(hash('sha256', json_encode($data)), 0, 16);
}

/**
 * The response fields shared by every test type's /config.php, merged with
 * the type-specific extras (stimuli/trials, rating_labels, allow_tie, ...).
 * Mirrors listen_and_rate/routers/api/_shared.py's _test_config_response().
 * The stimuli/trials are already in final order (presentation_order is
 * applied server-side in the type-specific builder), so nothing about
 * ordering is echoed to the browser.
 */
function base_config_response(array $data, array $extras): array
{
    return array_merge([
        'experiment_id' => $data['experiment_id'],
        // Which language the built-in UI chrome renders in ('en'/'ja'). Falls
        // back to 'en' for a bundle exported before this existed - mirrors
        // 'resume''s '?? [...]' fallback just below (same reasoning: this
        // file upgraded without re-running lar-export).
        'ui_language' => $data['ui_language'] ?? 'en',
        // Which per-answer measurements the frontend should take.
        'metrics' => $data['metrics'],
        // How long an interrupted session may be resumed for, in the
        // milliseconds the browser compares against Date.now(); the export
        // converted the config's hours (0 means resume is off). Falls back to
        // off (not a guessed window) for a bundle exported before this
        // existed - e.g. this file upgraded without re-running lar-export.
        'resume' => $data['resume'] ?? ['max_age_ms' => 0],
        'config_version' => config_version($data),
        'test_type' => $data['test_type'],
        'title' => $data['title'],
        'instructions' => $data['instructions'],
        // The HTML <audio preload> level ("none"/"auto"); the browser reads it
        // straight onto each <audio> element.
        'audio_preload' => $data['audio_preload'],
        // {stimulus_id: seconds}, baked in at export time so the time bar can
        // show clip length immediately (see _shared.py's _test_config_response).
        'durations' => $data['durations'],
        // Each form is one {title, fields} block, passed through unchanged -
        // the export tool always writes both, so no fallback is needed.
        'metadata' => $data['metadata'],
        'survey' => $data['survey'],
        'shortcuts' => $data['shortcuts'],
    ], $extras);
}

/**
 * Pair stimuli into AB trials by item, mirroring
 * listen_and_rate/config/ab.py's build_ab_trials(). Items not present in
 * exactly 2 stimuli are silently skipped (the config-load-time warning about
 * them, if any, was already emitted by the Python export tool). Shared by
 * CMOS, AB, and ABX, which all pair stimuli the same way.
 */
function group_ab_trials(array $stimuli): array
{
    $byItem = [];
    foreach ($stimuli as $s) {
        if (($s['item'] ?? '') !== '') {
            $byItem[$s['item']][] = $s;
        }
    }
    ksort($byItem);

    $trials = [];
    foreach ($byItem as $group) {
        if (count($group) !== 2) {
            continue;
        }
        usort($group, fn ($a, $b) => ($a['system'] ?? '') <=> ($b['system'] ?? ''));
        $trials[] = ['stimuli' => $group];
    }
    return $trials;
}

/** Apply per-session sampling to AB trials (one trial = one item's pair). */
function sample_ab_trials(array $trials, ?int $itemsPerSession): array
{
    return $itemsPerSession !== null
        ? sample_keep_order($trials, $itemsPerSession)
        : $trials;
}

/**
 * Whether the per-session presentation order should be shuffled.
 *
 * Mirrors BaseTestConfig.shuffle_order: "random" (the default) shuffles,
 * "fixed" keeps the configured order. Governs ordering only - the per-session
 * subset and within-trial position blinding are always randomized.
 */
function should_shuffle(array $data): bool
{
    return $data['presentation_order'] === 'random';
}

/**
 * Build the sampled (and, if configured, shuffled) pair-trial list shared by
 * CMOS's, AB's, and ABX's config responses.
 */
function sampled_pair_trials(array $data): array
{
    $trials = sample_ab_trials(
        group_ab_trials($data['stimuli']),
        $data['items_per_session'] ?? null
    );
    return should_shuffle($data) ? shuffle_stimuli($trials) : $trials;
}

// -- MOS -----------------------------------------------------------------

/**
 * Apply per-session sampling to the stimuli list, mirroring
 * listen_and_rate/routers/api/mos.py's _get_mos_test_config() sampling
 * logic. Exactly one of $stimuliPerSession/$itemsPerSession is expected
 * to be non-null (or neither, to use every stimulus).
 */
function sample_stimuli(array $stimuli, ?int $stimuliPerSession, ?int $itemsPerSession): array
{
    if ($itemsPerSession !== null) {
        return sample_by_item($stimuli, $itemsPerSession, fn ($s) => $s['item'] ?? '');
    }
    if ($stimuliPerSession !== null) {
        return sample_keep_order($stimuli, $stimuliPerSession);
    }
    return $stimuli;
}

/**
 * Build the /config.php response array for a MOS test from the static
 * config_data.php data. Only id/label/audio_url per stimulus is exposed -
 * see stimulus_to_public() for the blinding rationale.
 */
function build_mos_config_response(array $data): array
{
    $stimuli = sample_stimuli(
        $data['stimuli'],
        $data['stimuli_per_session'] ?? null,
        $data['items_per_session'] ?? null
    );
    if (should_shuffle($data)) {
        $stimuli = shuffle_stimuli($stimuli);
    }

    $toPublic = fn ($stimuli) => array_map('stimulus_to_public', $stimuli);
    return base_config_response($data, array_merge(
        [
            'stimuli' => $toPublic($stimuli),
            'rating_labels' => $data['rating_labels'],
        ],
        practice_extras($data, $data['stimuli'], $toPublic, 'practice_stimuli')
    ));
}

// -- DMOS ----------------------------------------------------------------

/**
 * Pair the reference stimulus with each non-reference system's stimulus, by
 * item, mirroring listen_and_rate/config/dmos.py's build_dmos_trials().
 * Each stimulus's 'reference' flag comes straight from config_data.php (see
 * lar-export) - unlike 'system', it is not sensitive: the listener is always
 * told which clip is the Reference.
 */
function group_dmos_trials(array $stimuli): array
{
    $byItem = [];
    foreach ($stimuli as $s) {
        if (($s['item'] ?? '') !== '') {
            $byItem[$s['item']][] = $s;
        }
    }
    ksort($byItem);

    $trials = [];
    foreach ($byItem as $group) {
        $reference = null;
        $tests = [];
        foreach ($group as $s) {
            if (!empty($s['reference'])) {
                $reference = $s;
            } else {
                $tests[] = $s;
            }
        }
        if ($reference === null) {
            continue;
        }
        foreach ($tests as $test) {
            $trials[] = ['reference' => $reference, 'test' => $test];
        }
    }
    return $trials;
}

/**
 * Apply per-session sampling to DMOS trials, mirroring
 * listen_and_rate/routers/api/dmos.py's _build_dmos_response_trials(): a DMOS
 * item can have several trials (one per test system), so
 * items_per_session samples whole items, keeping every test
 * system's trial for each chosen one.
 */
function sample_dmos_trials(array $trials, ?int $itemsPerSession): array
{
    return $itemsPerSession !== null
        ? sample_by_item($trials, $itemsPerSession, fn ($t) => $t['reference']['item'] ?? '')
        : $trials;
}

/** Map DMOS trials to their public {reference, test} response shape. */
function dmos_trials_to_public(array $trials): array
{
    return array_map(
        fn ($t) => [
            'reference' => stimulus_to_public($t['reference']),
            'test' => stimulus_to_public($t['test']),
        ],
        $trials
    );
}

/**
 * Build the /config.php response array for a DMOS test from the static
 * config_data.php data. Only id/label/audio_url per stimulus is exposed.
 * Unlike ABX, the Reference/Test roles are not blinded - the listener is
 * explicitly told which clip is the reference.
 */
function build_dmos_config_response(array $data): array
{
    $allTrials = group_dmos_trials($data['stimuli']);
    $trials = sample_dmos_trials($allTrials, $data['items_per_session'] ?? null);
    if (should_shuffle($data)) {
        $trials = shuffle_stimuli($trials);
    }

    return base_config_response($data, array_merge(
        [
            'trials' => dmos_trials_to_public($trials),
            'rating_labels' => $data['rating_labels'],
        ],
        practice_extras($data, $allTrials, 'dmos_trials_to_public')
    ));
}

// -- CMOS ----------------------------------------------------------------

/**
 * Map AB trials to the blinded {stimuli} shape shared by CMOS and AB; each
 * trial's pair order is shuffled so system A doesn't always appear first.
 */
function pair_trials_to_public(array $trials): array
{
    return array_map(
        fn ($t) => ['stimuli' => array_map('stimulus_to_public', shuffle_stimuli($t['stimuli']))],
        $trials
    );
}

/**
 * Build the /config.php response array for a CMOS test from the static
 * config_data.php data, mirroring listen_and_rate/routers/api/cmos.py's
 * _get_cmos_test_config(). Pairs stimuli by item across exactly 2
 * systems, same as AB - but unlike AB (which exposes 'allow_tie'), CMOS
 * exposes 'rating_labels'.
 */
function build_cmos_config_response(array $data): array
{
    return base_config_response($data, array_merge(
        [
            'trials' => pair_trials_to_public(sampled_pair_trials($data)),
            'rating_labels' => $data['rating_labels'],
        ],
        practice_extras($data, group_ab_trials($data['stimuli']), 'pair_trials_to_public')
    ));
}

// -- AB ------------------------------------------------------------------

/**
 * Build the /config.php response array for an AB test from the static
 * config_data.php data. Only id/label/audio_url per stimulus is exposed,
 * and each trial's pair order is blinded per trial.
 */
function build_ab_config_response(array $data): array
{
    return base_config_response($data, array_merge(
        [
            'trials' => pair_trials_to_public(sampled_pair_trials($data)),
            'allow_tie' => $data['allow_tie'] ?? true,
        ],
        practice_extras($data, group_ab_trials($data['stimuli']), 'pair_trials_to_public')
    ));
}

// -- ABX -----------------------------------------------------------------

/** Map AB trials to ABX's blinded {stimuli, x} shape, committing each trial's hidden X. */
function abx_trials_to_public(array $trials, string $secret): array
{
    return array_map(function ($t) use ($secret) {
        $stimuli = shuffle_stimuli($t['stimuli']);
        $idA = $stimuli[0]['id'];
        $idB = $stimuli[1]['id'];
        $matchedId = pick_one($stimuli)['id'];
        return [
            'stimuli' => array_map('stimulus_to_public', $stimuli),
            'x' => ['token' => commit_x($idA, $idB, $matchedId, $secret)],
        ];
    }, $trials);
}

/**
 * Build the /config.php response array for an ABX test from the static
 * config_data.php data. Only id/label/audio_url per stimulus is exposed, and
 * each trial's hidden "X" reference is represented only by an opaque
 * token (see x_token.php) - never a real stimulus id, so the
 * response never reveals which stimulus X duplicates.
 */
function build_abx_config_response(array $data): array
{
    $secret = hex2bin($data['x_secret']);
    $toPublic = fn ($trials) => abx_trials_to_public($trials, $secret);
    return base_config_response($data, array_merge(
        ['trials' => $toPublic(sampled_pair_trials($data))],
        practice_extras($data, group_ab_trials($data['stimuli']), $toPublic)
    ));
}

// -- XAB -----------------------------------------------------------------

/**
 * Group stimuli into one XAB trial per item - the reference stimulus
 * plus exactly 2 test-system stimuli - mirroring
 * listen_and_rate/config/xab.py's build_xab_trials(). Items missing
 * the reference or either test stimulus are silently skipped.
 */
function group_xab_trials(array $stimuli): array
{
    $byItem = [];
    foreach ($stimuli as $s) {
        if (($s['item'] ?? '') !== '') {
            $byItem[$s['item']][] = $s;
        }
    }
    ksort($byItem);

    $trials = [];
    foreach ($byItem as $group) {
        $reference = null;
        $tests = [];
        foreach ($group as $s) {
            if (!empty($s['reference'])) {
                $reference = $s;
            } else {
                $tests[] = $s;
            }
        }
        if ($reference === null || count($tests) !== 2) {
            continue;
        }
        $trials[] = ['reference' => $reference, 'stimuli' => $tests];
    }
    return $trials;
}

/** Map XAB trials to their blinded {reference, stimuli} shape; the A/B pair order is shuffled per trial. */
function xab_trials_to_public(array $trials): array
{
    return array_map(
        fn ($t) => [
            'reference' => stimulus_to_public($t['reference']),
            'stimuli' => array_map('stimulus_to_public', shuffle_stimuli($t['stimuli'])),
        ],
        $trials
    );
}

/**
 * Build the /config.php response array for an XAB test from the static
 * config_data.php data, mirroring listen_and_rate/routers/api/xab.py's
 * _get_xab_test_config(). The reference X is disclosed (never blinded);
 * the A/B pair order is blinded per trial, same as AB's shuffle. Unlike
 * ABX there is no commitment token - X is an independent reference
 * recording, not a hidden duplicate of A or B.
 */
function build_xab_config_response(array $data): array
{
    $allTrials = group_xab_trials($data['stimuli']);
    $trials = sample_ab_trials($allTrials, $data['items_per_session'] ?? null);
    if (should_shuffle($data)) {
        $trials = shuffle_stimuli($trials);
    }

    return base_config_response($data, array_merge(
        ['trials' => xab_trials_to_public($trials)],
        practice_extras($data, $allTrials, 'xab_trials_to_public')
    ));
}

// -- MUSHRA --------------------------------------------------------------

/**
 * Group stimuli into one MUSHRA trial per item, mirroring
 * listen_and_rate/config/mushra.py's build_mushra_trials(). Since the public
 * 'stimuli' list withholds 'system' names, completeness (every rateable
 * system present for an item) is checked by count against
 * $rateableSystemCount rather than by name, matching the guarantee that
 * each system contributes at most one stimulus per item.
 */
function group_mushra_trials(array $stimuli, int $rateableSystemCount): array
{
    $byItem = [];
    foreach ($stimuli as $s) {
        if (($s['item'] ?? '') !== '') {
            $byItem[$s['item']][] = $s;
        }
    }
    ksort($byItem);

    $trials = [];
    foreach ($byItem as $group) {
        $reference = null;
        $anchor    = null;
        $systems   = [];
        foreach ($group as $s) {
            if (!empty($s['reference'])) {
                $reference = $s;
            } elseif (!empty($s['anchor'])) {
                $anchor = $s;
            } else {
                $systems[] = $s;
            }
        }
        if (count($systems) + ($anchor !== null ? 1 : 0) !== $rateableSystemCount) {
            continue;
        }
        $trials[] = ['reference' => $reference, 'systems' => $systems, 'anchor' => $anchor];
    }
    return $trials;
}

/** The item a MUSHRA trial belongs to, regardless of which slot happens to carry it. */
function mushra_trial_item(array $trial): string
{
    return $trial['reference']['item']
        ?? $trial['systems'][0]['item']
        ?? $trial['anchor']['item']
        ?? '';
}

/**
 * Apply per-session sampling to MUSHRA trials, mirroring
 * listen_and_rate/routers/api/mushra.py's _get_mushra_test_config(): one trial per
 * item, so items_per_session samples whole trials directly.
 */
function sample_mushra_trials(array $trials, ?int $itemsPerSession): array
{
    return $itemsPerSession !== null
        ? sample_by_item($trials, $itemsPerSession, fn ($t) => mushra_trial_item($t))
        : $trials;
}

/**
 * Map MUSHRA trials to their blinded {reference, systems, anchor} shape;
 * the blind systems are reshuffled per trial, the anchor stays separate.
 */
function mushra_trials_to_public(array $trials): array
{
    return array_map(
        fn ($t) => [
            'reference' => $t['reference'] !== null ? stimulus_to_public($t['reference']) : null,
            'systems' => array_map('stimulus_to_public', shuffle_stimuli($t['systems'])),
            'anchor' => $t['anchor'] !== null ? stimulus_to_public($t['anchor']) : null,
        ],
        $trials
    );
}

/**
 * Build the /config.php response array for a MUSHRA test from the static
 * config_data.php data, mirroring listen_and_rate/routers/api/mushra.py's
 * _get_mushra_test_config(). Only id/label/audio_url per stimulus is
 * exposed. The reference (if any) is never blinded; the anchor (if any) is
 * kept out of the shuffled 'systems' array so the frontend can always render
 * it last and labeled "Anchor"; every other system is blind and reshuffled
 * per trial.
 */
function build_mushra_config_response(array $data): array
{
    $allTrials = group_mushra_trials($data['stimuli'], $data['mushra_rateable_system_count'] ?? 0);
    $trials = sample_mushra_trials($allTrials, $data['items_per_session'] ?? null);
    if (should_shuffle($data)) {
        $trials = shuffle_stimuli($trials);
    }

    return base_config_response($data, array_merge(
        [
            'trials' => mushra_trials_to_public($trials),
            'rating_labels' => $data['rating_labels'],
        ],
        practice_extras($data, $allTrials, 'mushra_trials_to_public')
    ));
}

// -- HTTP entry point ----------------------------------------------------

/**
 * Build the /config.php response array from the static config_data.php data,
 * dispatching to the test type's builder ('mos' is also the fallback for an
 * unrecognized test_type, matching save.php's normalization).
 */
function build_config_response(array $data): array
{
    return match ($data['test_type'] ?? 'mos') {
        'mos' => build_mos_config_response($data),
        'dmos' => build_dmos_config_response($data),
        'cmos' => build_cmos_config_response($data),
        'ab' => build_ab_config_response($data),
        'abx' => build_abx_config_response($data),
        'xab' => build_xab_config_response($data),
        'mushra' => build_mushra_config_response($data),
        default => build_mos_config_response($data),
    };
}

// Only run when this file is executed directly as an HTTP entry point (see
// save.php for the same guard and rationale).
if (realpath($_SERVER['SCRIPT_FILENAME'] ?? '') === __FILE__) {
    header('Content-Type: application/json; charset=utf-8');
    $data = include __DIR__ . '/config_data.php';
    echo json_encode(build_config_response($data));
}
