<?php

/**
 * save.php - listening test result persistence endpoint (PHP static deployment).
 *
 * Results are stored under the config's output.path (carried into
 * config_data.php as output_path by `make export`), resolved against this
 * bundle's own directory when relative - the default './results/' means the
 * results/ subdirectory alongside this file, whose raw .csv/.json files are
 * blocked from direct web access by a seeded .htaccess (Apache only - see
 * the README's Limitations section). An absolute output.path is used as-is,
 * e.g. to keep results outside the web root entirely.
 *
 * Output format (csv or json) and metadata field definitions are also read
 * from config_data.php. The system/item mapping is read from
 * stimulus_map.php, likewise generated by `make export` - neither of these
 * is served directly to the browser (config.php is, and deliberately omits
 * 'system' so listeners cannot see which system a stimulus belongs to
 * before rating it).
 * CSV:  <results dir>/{experiment_id}/{session_id}.csv  - one row per record
 * JSON: <results dir>/{experiment_id}/{session_id}.json - one object per session
 *
 * The experiment_id naming the directory comes from config_data.php, not from
 * the body: this bundle serves one experiment (see experiment_id_for).
 *
 * Expected POST body:
 *   {
 *     "session_id": "uuid-string",
 *     "test_type": "mos",
 *     "ratings": [{"stimulus_id": "...", "rating": 4}, ...],
 *     "metadata": {"listener": "Alice", ...},
 *     "survey": {"trial_count": "Appropriate", ...}
 *   }
 *
 * GET /save.php  - pre-flight check: verifies the results dir is writable.
 * POST /save.php - write per-session file under <results dir>/{experiment_id}/.
 *
 * The functions below are pure (no superglobals, no exit/echo) so they can
 * be exercised directly from PHPUnit (see frontend/tests/SaveTest.php).
 * handle_save_request() is the only part that touches superglobals/output,
 * and only runs when this file is executed directly (see the guard at the
 * bottom) - not when a test merely requires this file for its functions.
 */

require_once __DIR__ . '/x_token.php';

// AB/XAB outcome tokens: the winner/closer column records which SIDE of the
// stored pair was chosen (system_a / system_b), or a tie, as a positional
// token rather than a system name - so any system name ("tie", "A", "="
// included) is collision-free. Mirrors Python storage.OUTCOME_* exactly.
const OUTCOME_A   = 'a';
const OUTCOME_B   = 'b';
const OUTCOME_TIE = '=';

// -- Shared helpers ------------------------------------------------------

/** Thrown by the helpers below to signal a request-level error with an HTTP status. */
class SaveRequestError extends RuntimeException
{
    public function __construct(public readonly int $status, string $message)
    {
        parent::__construct($message);
    }
}

/**
 * Whether $s may be used as a results path component.
 *
 * Mirrors listen_and_rate/ids.py's ID_PATTERN/is_valid_id, including its
 * reason for rejecting rather than rewriting: rewriting is not injective (two
 * differently-named experiments could sanitize onto one directory), and it
 * would have to agree character for character with the FastAPI server or the
 * same experiment would write to two different directories depending on how
 * it was deployed. The /u modifier matters - without it the class is applied
 * per BYTE, so one multi-byte character would rewrite to several underscores
 * while Python rewrote it to one.
 *
 * '.' and '..' are excluded separately: the dot is allowed so an id like
 * "config.mos" works, and those two are directory references, not names.
 */
/**
 * Decimals a metric is stored with. Mirrors listen_and_rate/storage.py's
 * METRIC_DECIMALS - two, because what these measure is noisier than that.
 */
const METRIC_DECIMALS = 2;

function is_valid_id(string $s): bool
{
    if ($s === '.' || $s === '..') {
        return false;
    }
    return preg_match('/^[A-Za-z0-9._-]+$/u', $s) === 1;
}

/** @throws SaveRequestError (400) if $s cannot be used as a path component. */
function assert_valid_id(string $s, string $field): void
{
    if (!is_valid_id($s)) {
        throw new SaveRequestError(
            400,
            "{$field} must contain only letters, digits, '.', '-', or '_' "
            . "(and cannot be '.' or '..')"
        );
    }
}

/**
 * Namespace form answers with a column prefix ('metadata_'/'survey_') for
 * CSV storage, mirroring listen_and_rate/storage.py's METADATA_/SURVEY_
 * column prefixes: prefixed form columns can never collide with the
 * saver-written result columns and stay distinguishable from each other.
 * JSON results keep the raw keys (metadata/survey are nested objects there).
 */
function prefix_keys(string $prefix, array $values): array
{
    $prefixed = [];
    foreach ($values as $key => $value) {
        $prefixed[$prefix . $key] = $value;
    }
    return $prefixed;
}

/**
 * Resolve the results directory from config_data.php's output_path.
 *
 * Mirrors the FastAPI deployment's treatment of output.path so both
 * deployments share one layout (<deployment root>/<output.path>/): a
 * relative path is resolved against this bundle's own directory (the YAML
 * default './results/' therefore keeps the historical <bundle>/results
 * location), and an absolute path is used as-is (e.g. to keep results
 * outside the web root). A missing/empty output_path - a config_data.php
 * generated before this field existed - falls back to <bundle>/results.
 */
function resolve_results_dir(string $baseDir, ?string $outputPath): string
{
    if ($outputPath === null || $outputPath === '') {
        return $baseDir . '/results';
    }
    if ($outputPath[0] === '/') {
        return rtrim($outputPath, '/');
    }
    $relative = trim($outputPath, '/');
    if (str_starts_with($relative, './')) {
        $relative = substr($relative, 2);
    }
    return $baseDir . '/' . $relative;
}

/**
 * Detect the server's actual configured timezone identifier (e.g. "Asia/Tokyo").
 *
 * PHP's own date.timezone ini setting is not reliably configured on shared
 * hosts and often silently defaults to UTC even when the OS itself is set to
 * a different zone, so this reads the OS's timezone files directly instead
 * (the same source of truth the `date` shell command and Python's
 * datetime.now().astimezone() rely on) rather than assuming any fixed zone.
 */
function detect_server_timezone(
    string $fallback = 'UTC',
    string $timezoneFile = '/etc/timezone',
    string $localtimeLink = '/etc/localtime'
): string {
    $tz = @trim((string) @file_get_contents($timezoneFile));
    if ($tz !== '' && in_array($tz, DateTimeZone::listIdentifiers(), true)) {
        return $tz;
    }

    $link = @readlink($localtimeLink);
    if ($link !== false) {
        $marker = '/zoneinfo/';
        $pos = strpos($link, $marker);
        if ($pos !== false) {
            $candidate = substr($link, $pos + strlen($marker));
            if (in_array($candidate, DateTimeZone::listIdentifiers(), true)) {
                return $candidate;
            }
        }
    }

    return $fallback;
}

/**
 * Throws SaveRequestError(400) if any of $keys is answered more than once.
 *
 * Mirrors listen_and_rate/routers/api/_shared.py's _require_answered_once():
 * $keys identifies what each answer is about, so one listener cannot rate the
 * same thing twice in a single submission. See that function for why a repeat
 * is rejected rather than merged.
 */
function assert_answered_once(array $keys, string $name, string $unit): void
{
    $seen = [];
    $duplicated = [];
    foreach ($keys as $key) {
        if (isset($seen[$key])) {
            $duplicated[$key] = true;
        }
        $seen[$key] = true;
    }
    if ($duplicated !== []) {
        $list = array_keys($duplicated);
        sort($list);
        throw new SaveRequestError(
            400,
            "{$name} must answer each {$unit} once. Repeated: " . implode(', ', $list)
        );
    }
}

/** The key identifying what one submitted answer is about, per test type. */
function answer_key(string $testType, array $answer): string
{
    if (in_array($testType, ['cmos', 'ab', 'abx', 'xab'], true)) {
        // A trial is its pair, whichever order the client echoes the ids in.
        $ids = is_array($answer['stimulus_ids'] ?? null) ? $answer['stimulus_ids'] : [];
        $ids = array_map('strval', $ids);
        sort($ids, SORT_STRING);
        return implode('+', $ids);
    }
    if ($testType === 'dmos') {
        return ($answer['stimulus_id'] ?? '') . '+' . ($answer['reference_id'] ?? '');
    }
    return (string) ($answer['stimulus_id'] ?? '');
}

/**
 * Throws SaveRequestError(400) if the submitted body is missing the
 * non-empty ratings/choices list its test_type requires, or answers the same
 * stimulus/trial twice. Mirrors listen_and_rate/routers/api/_shared.py's
 * _require_non_empty()/_require_answered_once() guards.
 */
function validate_submission_shape(string $testType, array $data): void
{
    if (in_array($testType, ['cmos', 'ab', 'abx', 'xab'], true)) {
        if (empty($data['choices'])) {
            throw new SaveRequestError(400, 'choices must be a non-empty array');
        }
        $answers = $data['choices'];
        $name = 'choices';
        $unit = 'trial';
    } else {
        if (empty($data['ratings'])) {
            throw new SaveRequestError(400, 'ratings must be a non-empty array');
        }
        $answers = $data['ratings'];
        $name = 'ratings';
        $unit = $testType === 'dmos' ? 'trial' : 'stimulus';
    }
    if (!is_array($answers)) {
        throw new SaveRequestError(400, "{$name} must be a non-empty array");
    }
    $keys = [];
    foreach ($answers as $answer) {
        $keys[] = answer_key($testType, is_array($answer) ? $answer : []);
    }
    assert_answered_once($keys, $name, $unit);
}

/**
 * Validate submitted metadata against config.metadata field definitions, then
 * keep only declared keys so undeclared/malformed values never reach storage.
 * Mirrors listen_and_rate/routers/api/_shared.py's _validate_metadata().
 *
 * @throws SaveRequestError (400) on a missing required field, an invalid text
 *         value, or a select value outside its configured options.
 */
function validate_metadata(array $fields, array $submitted): array
{
    $meta = [];
    foreach ($fields as $field) {
        $key   = $field['key'];
        $value = $submitted[$key] ?? '';
        if ($value === '') {
            if (!empty($field['required'])) {
                throw new SaveRequestError(400, "Missing required metadata field: {$key}");
            }
            continue;
        }
        // A crafted body can send an array (or other non-string) here; reject
        // it as a clean 400 rather than letting preg_match()/in_array() raise
        // an uncaught TypeError (a blank 500). Mirrors the FastAPI backend,
        // whose Pydantic dict[str, str] typing already refuses a non-string.
        if (!is_string($value)) {
            throw new SaveRequestError(400, "Metadata field {$key} must be a string");
        }
        $type = $field['type'] ?? 'text';
        // \z, not $: PCRE's $ also matches before a trailing newline, which
        // the browser's JS regex does not - see _METADATA_TEXT_RE in
        // listen_and_rate/routers/api/_shared.py.
        if ($type === 'text' && !preg_match('/^[a-zA-Z0-9.-]+\z/', $value)) {
            throw new SaveRequestError(400, "Metadata field {$key} contains invalid characters");
        }
        if ($type === 'select' && !empty($field['options']) && !in_array($value, $field['options'], true)) {
            throw new SaveRequestError(400, "Metadata field {$key}: value is not one of the configured options");
        }
        $meta[$key] = $value;
    }
    return $meta;
}

/**
 * The metric names this experiment opted into, in column order.
 *
 * Mirrors listen_and_rate/config/base.py's MetricsConfig.enabled_keys(): a
 * client may measure whatever it likes, but only what the config asked for is
 * stored, so an unrequested value cannot reach the results.
 */
function enabled_metrics(array $configData): array
{
    $metrics = $configData['metrics'] ?? [];
    return is_array($metrics) ? array_keys(array_filter($metrics)) : [];
}

/**
 * The submitted answers, under whichever key this test type sends them.
 *
 * One answer produces exactly one stored row in every test type (MUSHRA sends
 * one per slider), so these line up index-for-index with the rows the builders
 * return - which is what lets the metrics be attached in one place afterwards
 * instead of threaded through all six builders.
 */
function submitted_answers(string $testType, array $data): array
{
    $key     = in_array($testType, ['cmos', 'ab', 'abx', 'xab'], true) ? 'choices' : 'ratings';
    $answers = $data[$key] ?? [];
    return is_array($answers) ? array_values($answers) : [];
}

/** One answer's metrics, keeping only the opted-in keys and rounding to ms. */
function answer_metrics(array $answer, array $keys): array
{
    $measured = [];
    foreach ($keys as $key) {
        $value = $answer[$key] ?? null;
        if (is_numeric($value)) {
            $measured[$key] = round((float) $value, METRIC_DECIMALS);
        }
    }
    return $measured;
}

/**
 * Append metrics_* columns to a built CSV table, mirroring the Python saver's
 * layout: last, after the answer columns, because they measure how the answer
 * was produced.
 */
function append_metrics_columns(array $fields, array $rows, array $answers, array $keys): array
{
    if ($keys === []) {
        return [$fields, $rows];
    }
    foreach ($keys as $key) {
        $fields[] = 'metrics_' . $key;
    }
    foreach ($rows as $i => $row) {
        $measured = answer_metrics($answers[$i] ?? [], $keys);
        foreach ($keys as $key) {
            // Fixed decimals, not PHP's float-to-string: that would write 9.0
            // as "9" where the FastAPI saver writes "9.00".
            $row[] = isset($measured[$key])
                ? sprintf('%.' . METRIC_DECIMALS . 'f', $measured[$key])
                : '';
        }
        $rows[$i] = $row;
    }
    return [$fields, $rows];
}

/** Nest a "metrics" object inside each built JSON entry (Python keeps it nested too). */
function append_metrics_json(array $entries, array $answers, array $keys): array
{
    if ($keys === []) {
        return $entries;
    }
    foreach ($entries as $i => $entry) {
        $measured = answer_metrics($answers[$i] ?? [], $keys);
        if ($measured !== []) {
            $entry['metrics'] = $measured;
        }
        $entries[$i] = $entry;
    }
    return $entries;
}

/**
 * Create/resolve the per-experiment results directory under $resultsDir.
 *
 * Resolves both directories to canonical paths before returning, so that a
 * crafted experiment_id (e.g. "..") cannot escape $resultsDir.
 *
 * @throws SaveRequestError (500) if directories cannot be created/resolved,
 *         or (400) if the resolved path would escape $resultsDir.
 */
function experiment_id_for(array $configData): string
{
    // From the bundle, never from the request. The same reasoning as the
    // AUTHORITATIVE test type below: this bundle serves one experiment, and a
    // client that names another one would file its results under that study.
    // Mirrors the FastAPI backend, which passes config.experiment_id to the
    // saver and ignores the field entirely.
    $id = (string) ($configData['experiment_id'] ?? '');
    return $id !== '' ? $id : 'results';
}

function resolve_experiment_dir(string $resultsDir, string $experimentId): string
{
    // Still checked: config_data.php is generated, but it is a plain file on
    // the server and this name becomes a path component.
    assert_valid_id($experimentId, 'experiment_id');

    if (!is_dir($resultsDir)) {
        mkdir($resultsDir, 0777, true);
    }
    $resultsReal = realpath($resultsDir);
    if ($resultsReal === false) {
        throw new SaveRequestError(500, 'Cannot resolve results directory');
    }

    $experimentDir = $resultsReal . '/' . $experimentId;
    if (!is_dir($experimentDir) && !mkdir($experimentDir, 0777, true)) {
        throw new SaveRequestError(
            500,
            "Cannot create {$experimentDir}. "
            . "Run on the server: mkdir -p {$experimentDir} && chmod 777 {$experimentDir}"
        );
    }

    $experimentReal = realpath($experimentDir);
    if ($experimentReal === false
        || strncmp($experimentReal . '/', $resultsReal . '/', strlen($resultsReal) + 1) !== 0
    ) {
        throw new SaveRequestError(400, 'Invalid experiment_id');
    }
    chmod($experimentReal, 0777);
    return $experimentReal;
}

/**
 * Validate one AB choice's stimulus_ids pair and return [$meta1, $meta2].
 *
 * @throws SaveRequestError (400) if the count isn't 2, an id is unknown, the
 *         pair isn't the same item, or both stimuli are the same system.
 */
function validate_ab_choice_pair(array $stimulusMap, array $stimulusIds): array
{
    if (count($stimulusIds) !== 2) {
        throw new SaveRequestError(400, 'Each AB choice must reference exactly 2 stimulus_ids');
    }
    [$id1, $id2] = $stimulusIds;
    $meta1 = $stimulusMap[$id1] ?? null;
    $meta2 = $stimulusMap[$id2] ?? null;
    if ($meta1 === null || $meta2 === null) {
        throw new SaveRequestError(400, 'Unknown stimulus IDs in AB choice');
    }
    if ($meta1['item'] !== $meta2['item'] || $meta1['system'] === $meta2['system']) {
        throw new SaveRequestError(400, 'stimulus_ids do not form a valid AB trial pair');
    }
    return [$meta1, $meta2];
}

/**
 * Open $path for exclusive creation - collected listener data is never
 * overwritten; a duplicate session_id (a resubmission, retry, or crafted
 * request) is refused with 409 instead. fopen('x') makes the create atomic,
 * so two simultaneous submissions for the same session cannot both pass (a
 * file_exists() pre-check would leave a window between check and write).
 * Mirrors listen_and_rate/storage.py's open(..., "x")/ResultExistsError.
 *
 * @throws SaveRequestError (409) if the file exists, (500) with
 *         $cannotWriteMessage if it cannot be created for another reason.
 * @return resource the opened file handle.
 */
function open_result_file_exclusive(string $path, string $cannotWriteMessage)
{
    $fp = @fopen($path, 'x');
    if ($fp !== false) {
        return $fp;
    }
    if (file_exists($path)) {
        throw new SaveRequestError(409, 'Results for this session already exist');
    }
    throw new SaveRequestError(500, $cannotWriteMessage);
}

/** @throws SaveRequestError (409) if the file exists, (500) if it cannot be written. */
function write_json_file(string $path, array $jsonData): void
{
    // PHP cannot tell an empty list from an empty map, so json_encode would
    // write "metadata": [] where the Python saver writes {}. The report reads
    // these as objects, so cast them and keep both backends' files identical.
    foreach (['metadata', 'survey'] as $key) {
        if (isset($jsonData[$key]) && is_array($jsonData[$key])) {
            $jsonData[$key] = (object) $jsonData[$key];
        }
    }
    $fp = open_result_file_exclusive($path, "Cannot write {$path}");
    $written = @fwrite($fp, json_encode(
        $jsonData,
        // PRESERVE_ZERO_FRACTION so a whole-number metric stays 9.0 rather
        // than collapsing to 9, matching what json.dump writes.
        JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_PRESERVE_ZERO_FRACTION
    ));
    fclose($fp);
    if ($written === false) {
        throw new SaveRequestError(500, "Cannot write {$path}");
    }
}

/** @throws SaveRequestError (409) if the file exists, (500) if it cannot be opened for writing. */
function write_csv_file(string $path, array $fields, array $rows, string $experimentDir): void
{
    $fp = open_result_file_exclusive(
        $path,
        "Cannot open {$path} for writing. "
        . "Run on the server: chmod 755 {$experimentDir}"
    );
    fputcsv($fp, $fields, ',', '"', '\\');
    foreach ($rows as $row) {
        fputcsv($fp, $row, ',', '"', '\\');
    }
    fclose($fp);
}

// -- MOS (its row builders below are also reused by DMOS and MUSHRA) -----

/**
 * Throws SaveRequestError(400) if any MOS rating references a stimulus_id
 * that is not in the stimulus map, mirroring listen_and_rate/routers/api/mos.py's
 * _submit_mos() unknown-ID check. Without this, a crafted submission could
 * smuggle arbitrary rows into the stored results.
 */
function validate_mos_ratings(array $stimulusMap, array $ratings): void
{
    $unknown = [];
    foreach ($ratings as $r) {
        $id = $r['stimulus_id'] ?? '';
        if (!isset($stimulusMap[$id])) {
            $unknown[] = $id;
        }
    }
    if ($unknown !== []) {
        sort($unknown, SORT_STRING);
        throw new SaveRequestError(400, 'Unknown stimulus IDs: ' . implode(', ', $unknown));
    }
}

/** Throws SaveRequestError(400) if any rating is outside the 1-5 MOS range. */
function validate_rating_range(array $ratings): void
{
    foreach ($ratings as $r) {
        $rating = intval($r['rating'] ?? 0);
        if ($rating < 1 || $rating > 5) {
            throw new SaveRequestError(400, "Rating out of range: $rating");
        }
    }
}

/** Build the assoc array to json_encode for JSON-format output. */
function build_json_result(array $data, array $meta, array $stimulusMap, string $ts): array
{
    $enriched = [];
    foreach ($data['ratings'] as $r) {
        // system/item come exclusively from the server-side stimulus map
        // - never from the submitted rating itself, which is client-controlled.
        $stim       = $stimulusMap[$r['stimulus_id'] ?? ''] ?? [];
        $enriched[] = [
            'system'    => $stim['system']    ?? '',
            'item' => $stim['item'] ?? '',
            'rating'    => intval($r['rating']),
        ];
    }
    return [
        'session_id' => $data['session_id'],
        'timestamp'  => $ts,
        'test_type'  => $data['test_type'],
        'metadata'   => $meta,
        'records'    => $enriched,
    ];
}

/**
 * Put the version of the tool that produced this bundle first in the columns.
 *
 * The version belongs to the software rather than to the session, so it goes
 * before session_id. Analysis refuses to combine result files that disagree
 * on it, because a rename or a changed column meaning would otherwise be
 * averaged in silently. Mirrors CSVResultSaver._BASE_FIELDS.
 *
 * An older bundle carries no version. The column is still written, empty, so
 * that "produced before this was recorded" stays distinguishable from
 * "produced by a version we know".
 */
function prepend_tool_version_columns(array $fields, array $rows, string $version): array
{
    $fields = array_merge(['tool_version'], $fields);
    foreach ($rows as $i => $row) {
        $rows[$i] = array_merge([$version], $row);
    }
    return [$fields, $rows];
}

/**
 * Lay the JSON result out in JSONResultSaver.save()'s key order.
 *
 * The version goes first for the reason above. The rest are ordered here
 * rather than left as the builders happened to produce them, because the
 * survey is attached afterwards and would otherwise land after the records -
 * making the same session look different depending on which backend served
 * it. An unexpected key keeps its value and follows at the end.
 */
function order_result_keys(array $result, string $version): array
{
    $ordered = ['tool_version' => $version];
    foreach (['session_id', 'timestamp', 'test_type', 'metadata', 'survey', 'records'] as $key) {
        if (array_key_exists($key, $result)) {
            $ordered[$key] = $result[$key];
        }
    }
    return $ordered + $result;
}

/** Build [$fields, $rows] for CSV-format output. */
function build_csv_rows(array $data, array $meta, array $metaKeys, array $stimulusMap, string $ts): array
{
    $fields = array_merge(
        ['session_id', 'timestamp', 'test_type'],
        $metaKeys,
        ['system', 'item', 'rating']
    );
    $rows = [];
    foreach ($data['ratings'] as $r) {
        $stim  = $stimulusMap[$r['stimulus_id'] ?? ''] ?? [];
        $row   = [$data['session_id'], $ts, $data['test_type']];
        foreach ($metaKeys as $k) {
            $row[] = $meta[$k] ?? '';
        }
        $row[]  = $stim['system']    ?? '';
        $row[]  = $stim['item'] ?? '';
        $row[]  = intval($r['rating']);
        $rows[] = $row;
    }
    return [$fields, $rows];
}

// -- DMOS ----------------------------------------------------------------

/**
 * Validate one DMOS rating's stimulus_id/reference_id pair, mirroring
 * listen_and_rate/routers/api/dmos.py's _submit_dmos() validation.
 *
 * @throws SaveRequestError (400) if reference_id is missing, either id is
 *         unknown, they don't share an item, reference_id doesn't
 *         actually belong to the reference system, or stimulus_id does.
 * @return array the test stimulus's metadata (system/item) - the row
 *         to store is built from this, exactly like a MOS rating's.
 */
function validate_dmos_rating(array $stimulusMap, array $r, string $referenceSystem): array
{
    $referenceId = $r['reference_id'] ?? null;
    if ($referenceId === null) {
        throw new SaveRequestError(400, 'reference_id is required for DMOS ratings');
    }
    $testMeta = $stimulusMap[$r['stimulus_id'] ?? ''] ?? null;
    $refMeta  = $stimulusMap[$referenceId] ?? null;
    if ($testMeta === null || $refMeta === null) {
        throw new SaveRequestError(400, 'Unknown stimulus IDs in DMOS rating');
    }
    if ($testMeta['item'] !== $refMeta['item']) {
        throw new SaveRequestError(400, 'stimulus_id/reference_id do not share the same item');
    }
    if ($refMeta['system'] !== $referenceSystem) {
        throw new SaveRequestError(400, 'reference_id must belong to the reference system');
    }
    if ($testMeta['system'] === $referenceSystem) {
        throw new SaveRequestError(400, "stimulus_id must not be the reference system's own stimulus");
    }
    return $testMeta;
}

// -- CMOS ----------------------------------------------------------------

/**
 * Validate one CMOS choice's stimulus_ids pair and rating, mirroring
 * listen_and_rate/routers/api/cmos.py's _submit_cmos() validation. Reuses
 * validate_ab_choice_pair() for the pair itself, since CMOS pairs stimuli
 * the same way AB does (2 systems, same item).
 *
 * @throws SaveRequestError (400) if the pair is invalid/unknown, rating is
 *         missing, or rating is outside -3..3.
 * @return array{0: array, 1: array} [$meta1, $meta2] - metadata for
 *         stimulus_ids[0]/[1] respectively (order preserved, unlike AB,
 *         since CMOS's rating direction depends on it).
 */
function validate_cmos_choice(array $stimulusMap, array $c): array
{
    [$meta1, $meta2] = validate_ab_choice_pair($stimulusMap, $c['stimulus_ids'] ?? []);
    if (!array_key_exists('rating', $c) || $c['rating'] === null) {
        throw new SaveRequestError(400, 'rating is required for CMOS choices');
    }
    $rating = intval($c['rating']);
    if ($rating < -3 || $rating > 3) {
        throw new SaveRequestError(400, "CMOS rating must be -3 to 3, got {$rating}");
    }
    return [$meta1, $meta2];
}

/** Build the assoc array to json_encode for JSON-format CMOS output. */
function build_cmos_json_result(array $data, array $meta, array $stimulusMap, string $ts): array
{
    $enriched = [];
    foreach ($data['choices'] as $c) {
        [$meta1, $meta2] = validate_cmos_choice($stimulusMap, $c);
        $pair = [$meta1['system'], $meta2['system']];
        sort($pair, SORT_STRING);
        // $c['rating'] means "stimulus_ids[1] relative to stimulus_ids[0]";
        // flip its sign when stimulus_ids[0] isn't the canonical (system_a) side.
        $rating     = $meta1['system'] === $pair[0] ? intval($c['rating']) : -intval($c['rating']);
        $enriched[] = [
            'system_a'  => $pair[0],
            'system_b'  => $pair[1],
            'item' => $meta1['item'],
            'rating'    => $rating,
        ];
    }
    return [
        'session_id' => $data['session_id'],
        'timestamp'  => $ts,
        'test_type'  => $data['test_type'],
        'metadata'   => $meta,
        'records'    => $enriched,
    ];
}

/** Build [$fields, $rows] for CSV-format CMOS output. */
function build_cmos_csv_rows(array $data, array $meta, array $metaKeys, array $stimulusMap, string $ts): array
{
    $fields = array_merge(
        ['session_id', 'timestamp', 'test_type'],
        $metaKeys,
        ['system_a', 'system_b', 'item', 'rating']
    );
    $rows = [];
    foreach ($data['choices'] as $c) {
        [$meta1, $meta2] = validate_cmos_choice($stimulusMap, $c);
        $pair = [$meta1['system'], $meta2['system']];
        sort($pair, SORT_STRING);
        $rating = $meta1['system'] === $pair[0] ? intval($c['rating']) : -intval($c['rating']);
        $row    = [$data['session_id'], $ts, $data['test_type']];
        foreach ($metaKeys as $k) {
            $row[] = $meta[$k] ?? '';
        }
        $row[]  = $pair[0];
        $row[]  = $pair[1];
        $row[]  = $meta1['item'];
        $row[]  = $rating;
        $rows[] = $row;
    }
    return [$fields, $rows];
}

// -- AB ------------------------------------------------------------------

/**
 * Validate all submitted AB choices, mirroring
 * listen_and_rate/routers/api/ab.py's _submit_ab() validation.
 *
 * @throws SaveRequestError (400) on an invalid pair, a selected_stimulus_id
 *         outside the pair, or a disallowed tie.
 */
function validate_ab_choices(array $choices, array $stimulusMap, bool $allowTie): void
{
    foreach ($choices as $c) {
        validate_ab_choice_pair($stimulusMap, $c['stimulus_ids'] ?? []);
        $selected = $c['selected_stimulus_id'] ?? null;
        if ($selected !== null && !in_array($selected, $c['stimulus_ids'], true)) {
            throw new SaveRequestError(400, 'selected_stimulus_id must be one of stimulus_ids');
        }
        if ($selected === null && !$allowTie) {
            throw new SaveRequestError(400, 'Ties are not allowed for this test');
        }
    }
}

/**
 * Positional outcome token for an AB choice: OUTCOME_TIE when nothing was
 * selected, else OUTCOME_A/OUTCOME_B for the chosen side of the sorted pair.
 * Mirrors listen_and_rate/routers/api/ab.py so any system name is safe.
 */
function ab_winner_token(?string $selected, array $stimulusMap, array $pair): string
{
    if ($selected === null) {
        return OUTCOME_TIE;
    }
    return $stimulusMap[$selected]['system'] === $pair[0] ? OUTCOME_A : OUTCOME_B;
}

/** Build the assoc array to json_encode for JSON-format AB output. */
function build_ab_json_result(array $data, array $meta, array $stimulusMap, string $ts): array
{
    $enriched = [];
    foreach ($data['choices'] as $c) {
        [$meta1, $meta2] = validate_ab_choice_pair($stimulusMap, $c['stimulus_ids']);
        $pair = [$meta1['system'], $meta2['system']];
        sort($pair, SORT_STRING);
        $selected   = $c['selected_stimulus_id'] ?? null;
        $enriched[] = [
            'system_a'  => $pair[0],
            'system_b'  => $pair[1],
            'item' => $meta1['item'],
            'winner'    => ab_winner_token($selected, $stimulusMap, $pair),
        ];
    }
    return [
        'session_id' => $data['session_id'],
        'timestamp'  => $ts,
        'test_type'  => $data['test_type'],
        'metadata'   => $meta,
        'records'    => $enriched,
    ];
}

/** Build [$fields, $rows] for CSV-format AB output. */
function build_ab_csv_rows(array $data, array $meta, array $metaKeys, array $stimulusMap, string $ts): array
{
    $fields = array_merge(
        ['session_id', 'timestamp', 'test_type'],
        $metaKeys,
        ['system_a', 'system_b', 'item', 'winner']
    );
    $rows = [];
    foreach ($data['choices'] as $c) {
        [$meta1, $meta2] = validate_ab_choice_pair($stimulusMap, $c['stimulus_ids']);
        $pair = [$meta1['system'], $meta2['system']];
        sort($pair, SORT_STRING);
        $selected = $c['selected_stimulus_id'] ?? null;
        $row      = [$data['session_id'], $ts, $data['test_type']];
        foreach ($metaKeys as $k) {
            $row[] = $meta[$k] ?? '';
        }
        $row[]  = $pair[0];
        $row[]  = $pair[1];
        $row[]  = $meta1['item'];
        $row[]  = ab_winner_token($selected, $stimulusMap, $pair);
        $rows[] = $row;
    }
    return [$fields, $rows];
}

// -- ABX -----------------------------------------------------------------

/**
 * Validate one ABX choice and resolve the ground truth via its x_token.
 *
 * @throws SaveRequestError (400) if the pair is invalid/unknown, the guess
 *         is missing or isn't one of the pair, or the x_token doesn't verify.
 * @return array{0: array, 1: array, 2: string} [$meta1, $meta2, $groundTruthId]
 */
function validate_abx_choice(array $stimulusMap, array $c, string $secret): array
{
    [$meta1, $meta2] = validate_ab_choice_pair($stimulusMap, $c['stimulus_ids'] ?? []);
    $selected = $c['selected_stimulus_id'] ?? null;
    if ($selected === null) {
        // ABX is forced-choice; unlike AB, null isn't a valid tie response.
        throw new SaveRequestError(400, 'selected_stimulus_id is required for ABX');
    }
    if (!in_array($selected, $c['stimulus_ids'], true)) {
        throw new SaveRequestError(400, 'selected_stimulus_id must be one of stimulus_ids');
    }
    [$id1, $id2] = $c['stimulus_ids'];
    $groundTruth = resolve_x($id1, $id2, $c['x_token'] ?? '', $secret);
    if ($groundTruth === null) {
        throw new SaveRequestError(400, 'Invalid or expired x_token');
    }
    return [$meta1, $meta2, $groundTruth];
}

/** Build the assoc array to json_encode for JSON-format ABX output. */
function build_abx_json_result(array $data, array $meta, array $stimulusMap, string $ts, string $secret): array
{
    $enriched = [];
    foreach ($data['choices'] as $c) {
        [$meta1, $meta2, $groundTruth] = validate_abx_choice($stimulusMap, $c, $secret);
        $pair = [$meta1['system'], $meta2['system']];
        sort($pair, SORT_STRING);
        $enriched[] = [
            'system_a'  => $pair[0],
            'system_b'  => $pair[1],
            'item' => $meta1['item'],
            'correct'   => $c['selected_stimulus_id'] === $groundTruth,
        ];
    }
    return [
        'session_id' => $data['session_id'],
        'timestamp'  => $ts,
        'test_type'  => $data['test_type'],
        'metadata'   => $meta,
        'records'    => $enriched,
    ];
}

/** Build [$fields, $rows] for CSV-format ABX output. */
function build_abx_csv_rows(array $data, array $meta, array $metaKeys, array $stimulusMap, string $ts, string $secret): array
{
    $fields = array_merge(
        ['session_id', 'timestamp', 'test_type'],
        $metaKeys,
        ['system_a', 'system_b', 'item', 'correct']
    );
    $rows = [];
    foreach ($data['choices'] as $c) {
        [$meta1, $meta2, $groundTruth] = validate_abx_choice($stimulusMap, $c, $secret);
        $pair = [$meta1['system'], $meta2['system']];
        sort($pair, SORT_STRING);
        $row = [$data['session_id'], $ts, $data['test_type']];
        foreach ($metaKeys as $k) {
            $row[] = $meta[$k] ?? '';
        }
        $row[]  = $pair[0];
        $row[]  = $pair[1];
        $row[]  = $meta1['item'];
        // Matches Python's str(True)/str(False), since storage.py's CSV
        // writer does the same for the equivalent MOS/AB row shape's values.
        // JSON-style lowercase tokens, matching the JSON output's native
        // boolean and Python's CSVResultSaver (see storage._csv_cell).
        $row[]  = ($c['selected_stimulus_id'] === $groundTruth) ? 'true' : 'false';
        $rows[] = $row;
    }
    return [$fields, $rows];
}

// -- XAB -----------------------------------------------------------------

/**
 * Validate one XAB choice's stimulus_ids pair and selection, mirroring
 * listen_and_rate/routers/api/xab.py's _submit_xab() validation. Reuses
 * validate_ab_choice_pair() for the pair itself; additionally rejects a
 * pair containing the reference system's stimulus (the rated pair must be
 * the two test systems) and a missing selection (forced choice - no tie).
 *
 * @throws SaveRequestError (400) if the pair is invalid/unknown, includes
 *         the reference stimulus, or the selection is missing/outside it.
 * @return array{0: array, 1: array} [$meta1, $meta2]
 */
function validate_xab_choice(array $stimulusMap, array $c, string $referenceSystem): array
{
    [$meta1, $meta2] = validate_ab_choice_pair($stimulusMap, $c['stimulus_ids'] ?? []);
    if ($meta1['system'] === $referenceSystem || $meta2['system'] === $referenceSystem) {
        throw new SaveRequestError(400, "stimulus_ids must not include the reference system's stimulus");
    }
    $selected = $c['selected_stimulus_id'] ?? null;
    if ($selected === null) {
        throw new SaveRequestError(400, 'selected_stimulus_id is required for XAB');
    }
    if (!in_array($selected, $c['stimulus_ids'], true)) {
        throw new SaveRequestError(400, 'selected_stimulus_id must be one of stimulus_ids');
    }
    return [$meta1, $meta2];
}

/**
 * Positional outcome token for an XAB choice: OUTCOME_A/OUTCOME_B for the
 * side of the sorted pair judged closer to the reference (XAB has no tie).
 * Mirrors listen_and_rate/routers/api/xab.py.
 */
function xab_closer_token(string $selected, array $stimulusMap, array $pair): string
{
    return $stimulusMap[$selected]['system'] === $pair[0] ? OUTCOME_A : OUTCOME_B;
}

/** Build the assoc array to json_encode for JSON-format XAB output. */
function build_xab_json_result(array $data, array $meta, array $stimulusMap, string $ts, string $referenceSystem): array
{
    $enriched = [];
    foreach ($data['choices'] as $c) {
        [$meta1, $meta2] = validate_xab_choice($stimulusMap, $c, $referenceSystem);
        $pair = [$meta1['system'], $meta2['system']];
        sort($pair, SORT_STRING);
        $enriched[] = [
            'system_a'  => $pair[0],
            'system_b'  => $pair[1],
            'item' => $meta1['item'],
            'closer'    => xab_closer_token($c['selected_stimulus_id'], $stimulusMap, $pair),
        ];
    }
    return [
        'session_id' => $data['session_id'],
        'timestamp'  => $ts,
        'test_type'  => $data['test_type'],
        'metadata'   => $meta,
        'records'    => $enriched,
    ];
}

/** Build [$fields, $rows] for CSV-format XAB output. */
function build_xab_csv_rows(array $data, array $meta, array $metaKeys, array $stimulusMap, string $ts, string $referenceSystem): array
{
    $fields = array_merge(
        ['session_id', 'timestamp', 'test_type'],
        $metaKeys,
        ['system_a', 'system_b', 'item', 'closer']
    );
    $rows = [];
    foreach ($data['choices'] as $c) {
        [$meta1, $meta2] = validate_xab_choice($stimulusMap, $c, $referenceSystem);
        $pair = [$meta1['system'], $meta2['system']];
        sort($pair, SORT_STRING);
        $row = [$data['session_id'], $ts, $data['test_type']];
        foreach ($metaKeys as $k) {
            $row[] = $meta[$k] ?? '';
        }
        $row[]  = $pair[0];
        $row[]  = $pair[1];
        $row[]  = $meta1['item'];
        $row[]  = xab_closer_token($c['selected_stimulus_id'], $stimulusMap, $pair);
        $rows[] = $row;
    }
    return [$fields, $rows];
}

// -- MUSHRA --------------------------------------------------------------

/**
 * Validate one MUSHRA rating's stimulus_id and value, mirroring
 * listen_and_rate/routers/api/mushra.py's _submit_mushra() per-item validation.
 *
 * @throws SaveRequestError (400) if the id is unknown, belongs to the
 *         reference system, or the rating is non-numeric or outside 0-100.
 * @return array the rated stimulus's metadata (system/item).
 */
function validate_mushra_rating(array $stimulusMap, array $r, ?string $referenceSystem): array
{
    $meta = $stimulusMap[$r['stimulus_id'] ?? ''] ?? null;
    if ($meta === null) {
        throw new SaveRequestError(400, 'Unknown stimulus ID in MUSHRA rating');
    }
    if ($referenceSystem !== null && $meta['system'] === $referenceSystem) {
        throw new SaveRequestError(400, "stimulus_id must not be the reference system's own stimulus");
    }
    // intval() would silently turn a non-numeric rating into 0 (a valid
    // score), so reject it explicitly - mirroring the FastAPI backend, where
    // Pydantic's int typing already refuses it.
    if (!is_numeric($r['rating'] ?? null)) {
        throw new SaveRequestError(400, 'MUSHRA rating must be a number');
    }
    $rating = intval($r['rating']);
    if ($rating < 0 || $rating > 100) {
        throw new SaveRequestError(400, "MUSHRA rating must be 0-100, got {$rating}");
    }
    return $meta;
}

/**
 * Validate that submitted MUSHRA ratings, grouped by item, cover every
 * rateable system, mirroring listen_and_rate/routers/api/mushra.py's
 * _submit_mushra() completeness check. Coverage only - a repeat collapses into
 * the same set, so "exactly once" is assert_answered_once()'s half of the job.
 *
 * @throws SaveRequestError (400) if any item is missing a system's rating or
 *         carries one for a system it should not.
 */
function validate_mushra_ratings_complete(array $stimulusMap, array $ratings, ?string $referenceSystem): void
{
    $rateableSystems = [];
    foreach ($stimulusMap as $meta) {
        $system = $meta['system'] ?? '';
        if ($system !== '' && $system !== $referenceSystem && !in_array($system, $rateableSystems, true)) {
            $rateableSystems[] = $system;
        }
    }
    sort($rateableSystems);

    $byItem = [];
    foreach ($ratings as $r) {
        $meta = $stimulusMap[$r['stimulus_id'] ?? ''] ?? null;
        if ($meta === null) {
            continue; // already rejected by validate_mushra_rating() above
        }
        $byItem[$meta['item']][$meta['system']] = true;
    }
    foreach ($byItem as $item => $systems) {
        $seen = array_keys($systems);
        sort($seen);
        if ($seen !== $rateableSystems) {
            throw new SaveRequestError(400, "Each item must rate every rateable system: {$item}");
        }
    }
}

// -- HTTP entry point ----------------------------------------------------

/** Handle the actual HTTP request: reads superglobals, writes headers/output. */
function handle_save_request(): void
{
    // Suppress PHP warnings/notices from corrupting JSON output.
    error_reporting(0);
    ini_set('display_errors', '0');

    // Use the server's actual timezone for the timestamp below, not whatever
    // (often UTC) PHP's own date.timezone ini setting happens to default to.
    date_default_timezone_set(detect_server_timezone());

    header('Content-Type: application/json; charset=utf-8');

    // Read output format/path, metadata field definitions, and the
    // AUTHORITATIVE test type from config_data.php - never trust the
    // client-submitted test_type for deciding how to validate/store.
    $config_data_path = __DIR__ . '/config_data.php';
    $config_data      = is_file($config_data_path) ? include $config_data_path : [];
    if (!is_array($config_data)) {
        $config_data = [];
    }

    $results_dir = resolve_results_dir(__DIR__, $config_data['output_path'] ?? null);

    // GET: pre-flight check - verify the results directory exists and is writable.
    if ($_SERVER['REQUEST_METHOD'] === 'GET') {
        if (!is_dir($results_dir) || !is_writable($results_dir)) {
            $reason = is_dir($results_dir) ? 'not writable' : 'missing or not accessible';
            http_response_code(503);
            echo json_encode(['error' =>
                "Results directory is {$reason}. "
                . "Run on the server: mkdir -p {$results_dir} && chmod 777 {$results_dir}"]);
            return;
        }
        echo json_encode(['status' => 'ok']);
        return;
    }

    if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
        http_response_code(405);
        echo json_encode(['error' => 'Method not allowed']);
        return;
    }

    $body = file_get_contents('php://input');
    $data = json_decode($body, true);

    $has_ratings = isset($data['ratings']) && is_array($data['ratings']);
    $has_choices = isset($data['choices']) && is_array($data['choices']);
    if (!is_array($data)
        || empty($data['session_id'])
        || empty($data['test_type'])
        || (!$has_ratings && !$has_choices)
    ) {
        http_response_code(422);
        echo json_encode(['error' => 'Invalid request body']);
        return;
    }

    try {
        $output_format = $config_data['output_format'] ?? 'csv';
        $test_type     = $config_data['test_type'] ?? 'mos';
        if (!in_array($test_type, ['mos', 'dmos', 'cmos', 'ab', 'abx', 'xab', 'mushra'], true)) {
            $test_type = 'mos';  // unrecognized config value: fall back to the default type
        }

        // Build stimulus lookup: id → {system, item} for enriching ratings.
        $stimulus_map_path = __DIR__ . '/stimulus_map.php';
        $stimulus_map = is_file($stimulus_map_path) ? include $stimulus_map_path : [];
        if (!is_array($stimulus_map)) {
            $stimulus_map = [];
        }

        $x_secret = hex2bin($config_data['x_secret'] ?? '');

        validate_submission_shape($test_type, $data);

        // CMOS, ABX, and XAB are absent here on purpose: their row builders
        // below (build_cmos_*/build_abx_*/build_xab_*) run the same per-choice
        // validation while building the rows, and every row is built before
        // anything is written - validating them here too would just do the
        // work twice.
        if ($test_type === 'mos') {
            validate_mos_ratings($stimulus_map, $data['ratings'] ?? []);
            validate_rating_range($data['ratings'] ?? []);
        } elseif ($test_type === 'dmos') {
            foreach ($data['ratings'] ?? [] as $r) {
                validate_dmos_rating($stimulus_map, $r, $config_data['reference_system'] ?? '');
            }
            validate_rating_range($data['ratings'] ?? []);
        } elseif ($test_type === 'ab') {
            validate_ab_choices($data['choices'] ?? [], $stimulus_map, $config_data['allow_tie'] ?? true);
        } elseif ($test_type === 'mushra') {
            foreach ($data['ratings'] ?? [] as $r) {
                validate_mushra_rating($stimulus_map, $r, $config_data['reference_system'] ?? null);
            }
            validate_mushra_ratings_complete(
                $stimulus_map,
                $data['ratings'] ?? [],
                $config_data['reference_system'] ?? null
            );
        }

        // Each form config is a {title, fields} block; only its fields drive
        // validation (the title is display-only, consumed by the frontend).
        $meta = validate_metadata(
            $config_data['metadata']['fields'],
            (is_array($data['metadata'] ?? null)) ? $data['metadata'] : []
        );
        // The post-test survey shares the metadata field schema and validator
        // (the two forms differ only in collection timing).
        $survey = validate_metadata(
            $config_data['survey']['fields'],
            (is_array($data['survey'] ?? null)) ? $data['survey'] : []
        );

        $experiment_dir  = resolve_experiment_dir($results_dir, experiment_id_for($config_data));
        assert_valid_id((string) $data['session_id'], 'session_id');
        $session_id_safe = $data['session_id'];
        // CSV columns are namespaced (metadata_*/survey_*, see prefix_keys);
        // the builders just lay out whatever keys they are handed, so the
        // merged prefixed map flows through them unchanged. JSON keeps the
        // raw keys inside its nested metadata/survey objects instead.
        $form      = array_merge(prefix_keys('metadata_', $meta), prefix_keys('survey_', $survey));
        $form_keys    = array_keys($form);
        $metrics_keys = enabled_metrics($config_data);
        // Baked in by `lar-export`. PHP cannot read the Python package's
        // version at request time, and the version that exported this bundle
        // is the one whose behaviour produced these results anyway.
        $tool_version = (string) ($config_data['tool_version'] ?? '');
        $ts        = date('c');

        if ($output_format === 'json') {
            $json_data = match ($test_type) {
                'mos', 'dmos' => build_json_result($data, $meta, $stimulus_map, $ts),
                'cmos' => build_cmos_json_result($data, $meta, $stimulus_map, $ts),
                'ab' => build_ab_json_result($data, $meta, $stimulus_map, $ts),
                'abx' => build_abx_json_result($data, $meta, $stimulus_map, $ts, $x_secret),
                'xab' => build_xab_json_result($data, $meta, $stimulus_map, $ts, $config_data['reference_system'] ?? ''),
                'mushra' => build_json_result($data, $meta, $stimulus_map, $ts),
            };
            // Survey answers and per-answer metrics are attached here, once,
            // rather than threaded through every per-test-type builder.
            $json_data['survey'] = $survey;
            // Every builder returns its rows under 'records', whatever key the
            // client sent them under - matching JSONResultSaver.
            $json_data['records'] = append_metrics_json(
                $json_data['records'],
                submitted_answers($test_type, $data),
                $metrics_keys
            );
            $json_data = order_result_keys($json_data, $tool_version);
            write_json_file($experiment_dir . '/' . $session_id_safe . '.json', $json_data);
        } else {
            [$fields, $rows] = match ($test_type) {
                'mos', 'dmos' => build_csv_rows($data, $form, $form_keys, $stimulus_map, $ts),
                'cmos' => build_cmos_csv_rows($data, $form, $form_keys, $stimulus_map, $ts),
                'ab' => build_ab_csv_rows($data, $form, $form_keys, $stimulus_map, $ts),
                'abx' => build_abx_csv_rows($data, $form, $form_keys, $stimulus_map, $ts, $x_secret),
                'xab' => build_xab_csv_rows($data, $form, $form_keys, $stimulus_map, $ts, $config_data['reference_system'] ?? ''),
                'mushra' => build_csv_rows($data, $form, $form_keys, $stimulus_map, $ts),
            };
            [$fields, $rows] = append_metrics_columns(
                $fields,
                $rows,
                submitted_answers($test_type, $data),
                $metrics_keys
            );
            [$fields, $rows] = prepend_tool_version_columns($fields, $rows, $tool_version);
            write_csv_file($experiment_dir . '/' . $session_id_safe . '.csv', $fields, $rows, $experiment_dir);
        }
    } catch (SaveRequestError $e) {
        http_response_code($e->status);
        echo json_encode(['error' => $e->getMessage()]);
        return;
    }

    echo json_encode(['status' => 'ok', 'session_id' => $data['session_id']]);
}

// Only run when this file is executed directly as an HTTP entry point.
// When PHPUnit (or anything else) merely requires this file for its
// functions, $_SERVER['SCRIPT_FILENAME'] points elsewhere, so this is false
// and no superglobals/output/exit paths are touched.
if (realpath($_SERVER['SCRIPT_FILENAME'] ?? '') === __FILE__) {
    handle_save_request();
}
