name: package

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - "**"

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 4
      matrix:
        include:
          - python: "3.11"
          - python: "3.14"

    steps:
      - name: Clone
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: ${{ matrix.python }}
          architecture: x64

      - name: uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0

      - name: Dependencies
        run: |
          sudo apt-get update -qq

      - name: Install
        run: make setup-dev

      - name: Check
        run: make lint

      - name: Test
        run: make test
